version: '3.8'
services:
  dev-db:
    image: postgres:13.2
    container_name: dev-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - dev-network
networks:
  dev-network:
